var RestaurantConstants = {
  RESTAURANTS_RECEIVED: "RESTAURANTS_RECEIVED",
  FOCUS_RESTAURANT: "FOCUS_RESTAURANT",
  UNFOCUS_ALL_RESTAURANTS: "UNFOCUS_ALL_RESTAURANTS"
};

module.exports = RestaurantConstants;
